"""PreToolUse guard — a deterministic safety net for destructive tool calls.

Classifies a pending Bash/PowerShell/Edit/Write/MultiEdit/Read/Grep into a risk tier and tells Claude
Code to **deny** (block) or **ask** (confirm) before it runs; low-risk calls emit nothing and fall
through to the normal permission flow. Ported from fann-core's permissions model. Pure
Python, cross-platform, no third-party deps.

Tiers:
  deny  — writing OR READING a secret file (.env*, *.pem/*.key, **/secrets/**,
          **/.secrets/**, credentials), copying/moving onto one through the shell, reading one via cat/type/
          Get-Content/etc. or an inline python/node one-liner, or a catastrophic shell command
          (rm -rf / ~ /* $HOME / drive-root, find -delete from root, fork bomb, dd to a device,
          mkfs, recursive chmod 777 on root). Blocked outright.
  ask   — consequential-but-legit: lockfile / CI-workflow writes; rm -rf <path>, find -delete,
          git force-push / reset --hard / clean -f / history rewrite, DB drop, package publish,
          piping a download into a shell. The user confirms. (Routine config like package.json/
          tsconfig is NOT gated — frequent and not dangerous; over-prompting gets the guard disabled.)
  allow — everything else; the hook stays silent so normal handling applies.

Escape hatch: `.caddis/config.toml [guard] allow = ["substr", ...]` may only DOWNGRADE an `ask`
to `allow` (it can never override a `deny`); it matches the command/path value. Use specific strings.

Kill switch: for users who run Claude Code with `bypassPermissions` and want zero additional
gating from caddis, the guard can be turned off entirely (bypasses ALL tiers, deny included) via:
  * env var `CADDIS_GUARD_DISABLED=1` (also 1/true/yes/on) — global, survives plugin updates.
  * `.caddis/config.toml [guard] enabled = false`  (or `mode = "off"`) — per-repo or user-level.
When disabled, the hook exits 0 immediately and every call falls through to normal permission handling.

Artifact dir: reads `.caddis/config.toml`.
The name is duplicated from scripts/claudster_config.py ON PURPOSE — this hook runs on EVERY tool
call and is safety-critical, so it stays import-free and self-contained (see the module list above).
"""
from __future__ import annotations

import fnmatch
import json
import os
import re
import sys
import time

# Functional identity, mirrored from scripts/claudster_config.py (see the note above).
_ARTIFACT_DIR = ".caddis"
_ENV_PREFIX = "CADDIS"

# ── protected-path rules (write → deny) ──────────────────────────────────────
_SECRET_BASENAMES = {"id_rsa", "id_dsa", "id_ecdsa", "id_ed25519", "credentials",
                     ".npmrc", ".pypirc", ".netrc", ".pgpass", ".htpasswd"}
_SECRET_SUFFIXES = (".pem", ".key", ".p12", ".pfx", ".keystore", ".jks")
_ENV_RE = re.compile(r"(^|/)\.env(\.|$)", re.I)
_ENV_EXAMPLE_RE = re.compile(r"\.env(\.[\w-]+)*\.(example|sample|template|dist)$", re.I)
_SECRET_GLOB_CANDIDATES = (
    ".env", ".env.local", ".env.production", ".env.development",
    "x.pem", "x.key", "id_rsa", "keys.env", "secrets.json",
)

# Lockfiles are normally regenerated by the package manager, so a hand-edit is unusual enough to
# confirm. Routine manifests (package.json/tsconfig) are deliberately NOT gated — too frequent, not risky.
_ASK_BASENAMES = {"package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock", "cargo.lock",
                  "uv.lock", "composer.lock", "gemfile.lock"}
_CI_WORKFLOW_RE = re.compile(r"(^|/)(\.github|\.gitea)/workflows/", re.I)


def classify_write(file_path: str) -> tuple[str, str]:
    """Risk tier (deny|ask|allow) + reason for writing/editing ``file_path``."""
    p = file_path.replace("\\", "/").rstrip(". ")
    parts = [seg.lower() for seg in p.split("/") if seg]
    base = parts[-1] if parts else ""

    if any(seg in ("secrets", ".secrets") for seg in parts):
        return "deny", f"writes into a secrets directory ({base})"
    if ".git" in parts[:-1]:
        return "deny", "writes into the .git internal directory"
    if _ENV_RE.search(p) and not _ENV_EXAMPLE_RE.search(p):
        return "deny", f"writes an environment/secret file ({base})"
    if base in _SECRET_BASENAMES or any(base.endswith(s) for s in _SECRET_SUFFIXES):
        return "deny", f"writes a credential/key file ({base})"

    if base in _ASK_BASENAMES:
        return "ask", f"edits a lockfile ({base})"
    if _CI_WORKFLOW_RE.search(p):
        return "ask", "edits a CI/CD workflow"
    return "allow", ""


def classify_read(file_path: str) -> tuple[str, str]:
    """Risk tier (deny|allow) + reason for reading ``file_path`` via the Read tool.

    Mirrors classify_write's env, credential, and secrets-directory rules, minus .git internals
    and the lockfile/CI `ask` tier. Reading .git internals is normal. Never
    returns "ask": Read is either fine or a secret disclosure, there's no confirm-and-proceed tier
    for a read that already happened by the time the user could answer.

    ``.envrc`` (direnv) is NOT ``.env``: _ENV_RE requires the char right after ".env" to be "." or
    end-of-segment, and "rc" is neither, so `.envrc` falls through to allow — intentional, direnv
    files are config, not the secret-bearing `.env`/`.env.*` family."""
    p = file_path.replace("\\", "/").rstrip(". ")
    parts = [seg.lower() for seg in p.split("/") if seg]
    base = parts[-1] if parts else ""

    if any(seg in ("secrets", ".secrets") for seg in parts[:-1]):
        return "deny", f"reads from a secrets directory ({base})"
    if _ENV_RE.search(p) and not _ENV_EXAMPLE_RE.search(p):
        return "deny", "reads a secret env file"
    if base in _SECRET_BASENAMES or any(base.endswith(s) for s in _SECRET_SUFFIXES):
        return "deny", f"reads a credential/key file ({base})"
    return "allow", ""


# ── bash rules ───────────────────────────────────────────────────────────────
# Catastrophic delete targets: a filesystem/home root or a *bare* drive root (C:\ ), NOT a drive
# subpath (E:\proj\dist falls through to ask).
_CATASTROPHIC_TARGET = re.compile(
    r"--no-preserve-root"
    # A closing bracket also ends the target: `echo $(rm -rf ~)` was ask, not deny (review catch).
    r"|(?:^|\s)(?:/|/\*|~/|~|\$\{?HOME\}?)(?:\s|$|;|&|\||[)}])"
    r"|(?:^|\s)[A-Za-z]:[\\/]?(?:\s|$|;|&|\||[)}])",
    re.I,
)
_FORK_BOMB = re.compile(r":\(\)\s*\{\s*:\s*\|\s*:\s*&\s*\}\s*;\s*:")


def _strip_quotes(s: str) -> str:
    """Drop quotes so quoted flags/targets still match (rm '-rf' \"/\" → rm -rf /)."""
    return s.replace('"', "").replace("'", "")


def _has_flag(cmd: str, letter: str, longname: str) -> bool:
    """True if `cmd` carries the short flag (e.g. -rf / -r) or the long flag (--recursive)."""
    return bool(re.search(rf"(?:^|\s)-\w*{letter}\w*\b", cmd, re.I)) or longname in cmd.lower()


def _is_rm_recursive_force(cmd: str) -> bool:
    if not re.search(r"\brm\b", cmd):
        return False
    return _has_flag(cmd, "r", "--recursive") and _has_flag(cmd, "f", "--force")


def _is_win_recursive_delete(cmd: str) -> bool:
    """Native Windows recursive delete — the POSIX ``rm`` path is handled by _is_rm_recursive_force.

    Catches PowerShell ``Remove-Item -Recurse -Force`` (and the Remove-Item aliases ri/rmdir/rd/del/
    erase) plus cmd.exe ``rmdir``/``rd``/``del``/``erase`` with the ``/s`` recurse-subdirectories switch.
    This is a Windows-primary environment, so these are the real footguns the POSIX rules miss."""
    if not re.search(r"(?:^|[\s;&|(])(?:remove-item|ri|rmdir|rd|del|erase)\b", cmd, re.I):
        return False
    ps_recurse_force = bool(re.search(r"(?:^|\s)-rec\w*", cmd, re.I)) and bool(re.search(r"(?:^|\s)-for\w*", cmd, re.I))
    cmd_slash_s = bool(re.search(r"(?:^|\s)/s\b", cmd, re.I))
    return ps_recurse_force or cmd_slash_s


_FIND_DELETE = r"\bfind\b.*?(?:-delete\b|-exec\s+rm\b)"
# Line continuations join a statement across physical lines: bash `\` and PowerShell backtick.
_CONTINUATION = re.compile(r"[\\`]\r?\n")


def _statements(c: str) -> list[str]:
    """Split a command on `;`, `&&`, `||` and newlines — ONLY at the top level.

    A separator inside quotes (`bash -c 'cd ~; rm -rf .'`), inside a subshell or block
    (`(cd ~; rm -rf .)`), or after a line continuation does not end a statement. The first version
    split on every one, and turned those real root deletes from deny into ask — a silent allow
    under deny-only. An unclosed quote or bracket keeps the rest as one statement, which errs
    toward deny. A pipe is never a separator: `find / | xargs rm -rf` is one statement. Quotes are
    stripped per statement afterwards, as the whole-command rules do.
    """
    c = _CONTINUATION.sub(" ", c)
    out: list[str] = []
    cur: list[str] = []
    quote, depth, i = "", 0, 0
    while i < len(c):
        ch = c[i]
        if quote:
            quote = "" if ch == quote else quote
        elif ch in "'\"":
            quote = ch
        elif ch in "({":
            depth += 1
        elif ch in ")}" and depth:
            depth -= 1
        elif depth == 0 and (ch in ";\n" or c[i:i + 2] in ("&&", "||")):
            out.append("".join(cur))
            cur = []
            i += 1 if ch in ";\n" else 2
            continue
        cur.append(ch)
        i += 1
    out.append("".join(cur))
    return [_strip_quotes(s) for s in out]


def _catastrophic_statement(c: str) -> str:
    """The deny reason when ONE statement both destroys recursively and names a root, else ''.

    Tested per statement, not per command. Testing "is there a recursive delete" and "is there a
    root-looking token" each across the whole command denied a scratchpad cleanup because an
    unrelated `~` or `C:` sat on another line (found 2026-09-10). The agent then ran the same
    delete inside the projects directory instead, where a junction is actually dangerous."""
    for seg in _statements(c):
        if not _CATASTROPHIC_TARGET.search(seg):
            continue
        sl = seg.lower()
        if _is_rm_recursive_force(seg):
            return "recursive force-delete of a root/home path (rm -rf)"
        if re.search(_FIND_DELETE, sl):
            return "find -delete from a root/home path"
        if _is_win_recursive_delete(seg):
            return "recursive force-delete of a root/home path (Windows Remove-Item/rmdir)"
        if (re.search(r"\bchmod\b", sl) and _has_flag(seg, "r", "--recursive")
                and re.search(r"\b0?777\b", sl)):
            return "recursive chmod 777 on a root path"
    return ""


# Shell constructs that WRITE to a named target: redirections, and the usual suspects that take
# a path argument. Matching the target lets classify_write judge it, so the shell path and the
# Write/Edit path can never disagree about what counts as a secret.
_SHELL_WRITE_TARGET = re.compile(
    r"""(?:
          >>?\s*(?P<redir>[^\s|;&<>]+)                      # > file   >> file
        | \|\s*tee\s+(?:-a\s+)?(?P<tee>[^\s|;&<>]+)          # | tee file
        | -(?:Path|FilePath|LiteralPath)\s+(?P<ps>[^\s|;&]+) # Set-Content -Path file
        | \bOut-File\s+(?P<outfile>[^\s|;&]+)                # Out-File file
    )""",
    re.IGNORECASE | re.VERBOSE,
)


def _shell_write_targets(command: str) -> list[str]:
    """Every path this command appears to write to. Best-effort by design: a miss degrades to the
    old behaviour, it never invents a denial."""
    out: list[str] = []
    for m in _SHELL_WRITE_TARGET.finditer(command):
        for val in m.groupdict().values():
            if val:
                out.append(val.strip("'\"" ))
    return out


_HEREDOC_MARKER = re.compile(
    r"<<(-?)[ \t]*(?:'([A-Za-z_][A-Za-z_0-9]*)'|\"([A-Za-z_][A-Za-z_0-9]*)\"|([A-Za-z_][A-Za-z_0-9]*))"
)
_HEREDOC_INTERPRETER = re.compile(
    r"^\s*(?:\S*/)?(?:bash|sh|zsh|dash|python|python3|py|node|ruby|perl|pwsh|powershell)\b",
    re.I,
)


def _unquoted_at(line: str, position: int) -> bool:
    """Whether a token at position is outside single and double quotes on this line."""
    quote = ""
    escaped = False
    for char in line[:position]:
        if escaped:
            escaped = False
        elif char == "\\" and quote != "'":
            escaped = True
        elif quote:
            if char == quote:
                quote = ""
        elif char in "'\"":
            quote = char
    return not quote and not escaped


def _without_heredoc_bodies(command: str) -> str:
    """Skip complete data-only heredocs; preserve executable and incomplete bodies."""
    lines = command.splitlines(keepends=True)
    kept: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        markers = []
        executable = False
        for marker in _HEREDOC_MARKER.finditer(line):
            pos = marker.start()
            if (pos and not (line[pos - 1].isspace() or line[pos - 1] in ";&|")
                    or not _unquoted_at(line, pos)):
                continue
            markers.append((next(group for group in marker.groups()[1:] if group is not None),
                            marker.group(1) == "-"))
            owner = re.split(r"[;&|]", line[:pos])[-1]
            executable |= bool(_HEREDOC_INTERPRETER.match(owner))
        if not markers:
            kept.append(line)
            i += 1
            continue
        end = i
        for tag, strip_tabs in markers:
            end += 1
            while end < len(lines):
                candidate = lines[end].rstrip("\r\n")
                if (candidate.lstrip("\t") if strip_tabs else candidate) == tag:
                    break
                end += 1
            if end == len(lines):
                return command
        kept.extend(lines[i:end + 1] if executable else [line])
        i = end + 1
    return "".join(kept)


# ── Phase 6: reading or copying onto a secret env file through the shell ─────
# Match copy/move verbs as whole tokens. Source and destination paths are checked below with the
# same path classifiers used by Read and Write.
_COPY_DEST = re.compile(r"(?i)(?:cp|mv|copy|move|copy-item|move-item)\Z")

# These verbs take file operands. Pattern tools (select-string/sls, grep/rg/findstr/awk/sed) take
# search patterns too, so matching an env-looking argument would block ordinary searches.
# Known limits: free text containing both a verb and `.env` (for example a commit message saying
# `never cat .env`) is denied; `git diff .env`, `git log -p .env`, bare `tee .env`, and
# `docker --env-file` are not blocked. Command substitution
# (`cat $(echo .env)`), PowerShell .NET file calls
# (`[IO.File]::ReadAllText`), and scripts that open the file themselves are not parsed here.
_ENV_READ = re.compile(
    r"(?i)(?:cat|type|more|less|head|tail|get-content|gc|base64|xxd|od|strings|hexdump|sort|nl|tac|source|\.)\Z"
)
_INPUT_REDIRECT = re.compile(r"(?<!<)<(?!<)\s*([^\s|;&<>]+)")

# python/node/etc. run inline with -c/-e that touches a `.env*` file, e.g. `open('.env')`.
# The mandatory [\s'"/\\] immediately before "\.env" is load-bearing: without it, `.env` would
# match inside `process.env.HOME` (preceded by "s" from "process") and deny an ordinary command
# that merely mentions an environment VARIABLE, not the FILE. Found while testing this phase.
_INLINE_ENV = re.compile(
    r"(?i)\b(python\d?|py|node|ruby|perl)\b\s+(-c|-e)\s+.*[\s'\"/\\]\.env"
    r"(?!\.(example|sample|template|dist))\b",
    re.DOTALL,
)


def _copy_segments(c: str) -> list[str]:
    """Segments of ``c`` split on ``;``, ``&&``, a bare newline and a bare ``|`` (quote/paren-aware).

    Unlike ``_statements`` (used for the catastrophic-delete check), a pipe IS a boundary here:
    `some_cmd | cp x .env` still has `cp x .env` naming its own destination at the end of ITS
    segment, and `_COPY_DEST`'s trailing `$` anchor needs that segment on its own to match."""
    c = _CONTINUATION.sub(" ", c)
    out: list[str] = []
    cur: list[str] = []
    quote, depth, i = "", 0, 0
    while i < len(c):
        ch = c[i]
        if quote:
            quote = "" if ch == quote else quote
        elif ch in "'\"":
            quote = ch
        elif ch in "({":
            depth += 1
        elif ch in ")}" and depth:
            depth -= 1
        elif depth == 0 and (ch in ";\n|" or c[i:i + 2] == "&&"):
            out.append("".join(cur))
            cur = []
            i += 2 if c[i:i + 2] == "&&" else 1
            continue
        cur.append(ch)
        i += 1
    out.append("".join(cur))
    return [_strip_quotes(s).strip() for s in out]


def _shell_env_access(command: str) -> tuple[str, str]:
    """Check simple shell file operands in one pass per command segment."""
    for seg in _copy_segments(command):
        # Redirection can precede or follow the command: `< .env cat` and `cat < .env`.
        for match in _INPUT_REDIRECT.finditer(seg):
            if classify_read(match.group(1))[0] == "deny":
                return "deny", "shell command reads a secret env file"

        words = seg.split()
        for index, word in enumerate(words):
            if word.lower() == "dd":
                for arg in words[index + 1:]:
                    if arg.startswith("if=") and classify_read(arg[3:])[0] == "deny":
                        return "deny", "shell command reads a secret env file"
                break

            if word.lower() == "git" and index + 1 < len(words) and words[index + 1].lower() == "show":
                for arg in words[index + 2:]:
                    if ":" in arg and classify_read(arg.split(":", 1)[1])[0] == "deny":
                        return "deny", "shell command reads a secret env file"
                break

            if _COPY_DEST.fullmatch(word):
                operands: list[str] = []
                destination = ""
                i = index + 1
                while i < len(words):
                    arg = words[i]
                    if arg.lower() in ("-path", "-literalpath", "-source", "-destination") and i + 1 < len(words):
                        if arg.lower() == "-destination":
                            destination = words[i + 1]
                        else:
                            operands.append(words[i + 1])
                        i += 2
                    elif not arg.startswith("-"):
                        operands.append(arg)
                        i += 1
                    else:
                        i += 1
                if not destination and len(operands) >= 2:
                    destination = operands.pop()
                if destination and classify_write(destination)[0] == "deny":
                    return "deny", f"shell command copies onto a secret file ({destination})"
                if any(classify_read(source)[0] == "deny" for source in operands):
                    return "deny", "shell command copies a secret env file"
                break

            if _ENV_READ.fullmatch(word):
                if any(classify_read(path)[0] == "deny" for path in words[index + 1:]):
                    return "deny", "shell command reads a secret env file"
                break
    return "allow", ""


def classify_bash(command: str) -> tuple[str, str]:
    """Risk tier (deny|ask|allow) + reason for a shell command."""
    c = command.strip()
    data_free = _without_heredoc_bodies(c)
    cl = c.lower()
    n = _strip_quotes(c)          # quote-normalized: defeats `rm '-rf' "/"` evasion
    nl = n.lower()

    # ── deny: writing a secret through the shell ──
    # classify_write denied `.env` and credential files; classify_bash had no equivalent, so the
    # SAME file was denied via Edit and waved through via `echo ... > .env`. Observed live: a phase
    # blocked on Edit, then written by a shell command minutes later. Delegating to classify_write
    # rather than restating its patterns is the point — two copies of a secret list would drift.
    for _target in _shell_write_targets(data_free):
        _tier, _why = classify_write(_target)
        if _tier == "deny":
            return "deny", f"shell command {_why}"

    # ── deny: copying or reading a secret env file through the shell ──
    _tier, _reason = _shell_env_access(_strip_quotes(data_free))
    if _tier == "deny":
        return _tier, _reason

    # ── deny: an inline python/node/etc. one-liner that touches a secret env file ──
    if _INLINE_ENV.search(c):
        return "deny", "inline interpreter touches a secret env file"

    rm_rf = _is_rm_recursive_force(n)
    find_delete = bool(re.search(_FIND_DELETE, nl))
    win_del = _is_win_recursive_delete(n)

    # ── deny: catastrophic ──
    why = _catastrophic_statement(c)
    if why:
        return "deny", why
    if re.search(r"\brmtree\s*\(\s*['\"]?(?:/|~|[A-Za-z]:\\?)['\"]?\s*\)", c, re.I):
        return "deny", "recursive tree delete of a root/home path (rmtree)"
    if _FORK_BOMB.search(c):
        return "deny", "fork bomb"
    if re.search(r"\bdd\b.*\bof=/dev/", nl) or re.search(r"\bmkfs", nl) or re.search(r">\s*/dev/sd[a-z]", nl):
        return "deny", "writes directly to a disk device"

    # ── ask: destructive-but-legit ──
    if rm_rf:
        return "ask", "recursive force-delete (rm -rf)"
    if find_delete:
        return "ask", "find with -delete / -exec rm"
    if win_del:
        return "ask", "recursive delete (Windows Remove-Item -Recurse / rmdir /s)"
    # git rules tolerate intervening options (e.g. `git -c k=v push --force`) but stay within one
    # command segment (the [^;&|]* won't cross a ; && || into an unrelated command). The trailing
    # `+\S` catches a force-push via refspec (`git push origin +main`), not just the --force flags.
    if re.search(r"\bgit\b[^;&|]*\bpush\b[^;&|]*(--force\b|--force-with-lease\b|(?:^|\s)-f\b|(?:^|\s)\+\S)", c):
        return "ask", "git force-push"
    if re.search(r"\bgit\b[^;&|]*\breset\s+--hard\b", c):
        return "ask", "git reset --hard"
    if re.search(r"\bgit\b[^;&|]*\bclean\b[^;&|]*(?:^|\s)-\w*f", c):
        return "ask", "git clean (force)"
    if re.search(r"\bgit\b[^;&|]*\bfilter-(repo|branch)\b", c):
        return "ask", "git history rewrite"
    if re.search(r"\b(drop\s+(table|database|schema)|truncate\s+table)\b", cl):
        return "ask", "destructive SQL (drop/truncate)"
    if re.search(r"\b(npm|yarn|pnpm)\s+publish\b|\btwine\s+upload\b|\bcargo\s+publish\b", cl):
        return "ask", "publishing a package"
    if re.search(r"\b(curl|wget|iwr|invoke-webrequest)\b[^|]*\|\s*(sudo\s+)?(sh|bash|zsh|iex|python)\b", cl):
        return "ask", "piping a download into a shell"
    return "allow", ""


def decide(tool_name: str, tool_input, allow_patterns: list[str]) -> tuple[str, str]:
    """Top-level decision. Classify FIRST; the allow escape hatch may only DOWNGRADE an `ask` to
    `allow` (never override a `deny`), and it matches the command/path value — not the JSON envelope —
    so a key name like "command" can't disable the guard. Never raises on a malformed payload."""
    if not isinstance(tool_input, dict):
        return "allow", ""

    if tool_name in ("Write", "Edit", "MultiEdit"):
        target = str(tool_input.get("file_path") or tool_input.get("path") or "")
        tier, reason = classify_write(target) if target else ("allow", "")
    elif tool_name in ("Bash", "PowerShell"):
        # PowerShell is a DISTINCT tool on Windows-primary hosts. Classifying only "Bash" meant
        # `Remove-Item -Recurse -Force <root>` bypassed every tier — while _is_win_recursive_delete
        # below exists for precisely those commands. The rule could never fire on the tool that
        # actually issues them. Verified live before fixing.
        target = str(tool_input.get("command", ""))
        tier, reason = classify_bash(target)
    elif tool_name == "Read":
        # Read never writes, so it only ever needs classify_read's deny/allow — no ask tier, no
        # lockfile/CI rules (reading a lockfile isn't consequential; writing one is).
        target = str(tool_input.get("file_path") or tool_input.get("path") or "")
        tier, reason = classify_read(target) if target else ("allow", "")
    elif tool_name == "Grep":
        target = tool_input.get("path") or tool_input.get("glob") or ""
        if not isinstance(target, str):
            return "allow", ""
        if tool_input.get("path"):
            base = target.replace("\\", "/").rstrip("/ .").split("/")[-1].lower()
            tier, reason = (("deny", "searches a secrets directory") if base in ("secrets", ".secrets")
                            else classify_read(target))
        elif any(char in target for char in "*?[]{}!"):
            pattern = target.replace("\\", "/").split("/")[-1].lower()
            tier, reason = (("deny", "search glob can match a secret file")
                            if any(fnmatch.fnmatchcase(name, pattern) for name in _SECRET_GLOB_CANDIDATES)
                            else ("allow", ""))
        else:
            tier, reason = classify_read(target) if target else ("allow", "")
    else:
        return "allow", ""

    if tier == "ask" and any(pat and pat.lower() in target.lower() for pat in allow_patterns):
        return "allow", ""
    return tier, reason


# ── the shared-tree lock during a spawn-session handover ─────────────────────
# `spawn-session.md` told the child not to move the shared checkout while both sessions are live.
# The parent pasted it verbatim and the successor switched branches within the hour (2026-09-10);
# four files the parent had corrected reverted under it. A rule that has to be remembered is not a
# gate, so while a handshake is open the guard refuses the git commands that move or discard the
# tree. DENY, not ask: deny-only mode turns every ask into a silent allow, and that is the mode the
# failure happened in.
#
# The verb must be git's SUBCOMMAND (first word after global options), so `git commit -m "reset x"`
# and `git worktree add ... -b feat` pass. `stash list` / `stash show` only read.
_TREE_MOVING_GIT = re.compile(
    r"\bgit(?:\s+-[Cc]\s+\S+|\s+--?[\w-]+(?:=\S+)?)*\s+"
    r"(?:switch|checkout|restore|rebase|reset|clean|stash(?!\s+(?:list|show)\b))(?=\s|$|[;&|])",
    re.I,
)
# Older than this is an abandoned handshake, not a live one — two REJECTs end a handshake that
# `close` can never accept, and it must not lock the tree forever.
_HANDSHAKE_LIVE_S = 24 * 3600


def _open_handshake(start: str) -> str:
    """Id of a spawn-session handshake still open in the repo holding ``start``, or ''."""
    here = os.path.abspath(start)
    while True:
        d = os.path.join(here, _ARTIFACT_DIR, "spawn-session")
        if os.path.isdir(d):
            now = time.time()
            for name in sorted(os.listdir(d)):
                if not name.endswith("-handshake.json"):
                    continue
                try:
                    with open(os.path.join(d, name), encoding="utf-8") as fh:
                        st = json.load(fh)
                except Exception:
                    continue
                # `tree_lock` is written by handshakes opened since the lock existed. Older files
                # never stamped `closed_at`, so without this opt-in a handshake finished under the
                # old code would lock a live session's tree — measured on a real one, 11h old.
                if not st.get("tree_lock") or st.get("closed_at"):
                    continue
                if now - float(st.get("opened_at", 0)) > _HANDSHAKE_LIVE_S:
                    continue
                return str(st.get("id") or name[: -len("-handshake.json")])
            return ""
        parent = os.path.dirname(here)
        if parent == here:
            return ""
        here = parent


def tree_lock_reason(command: str, root: str) -> str:
    """The deny reason when ``command`` would move a checkout a live handshake shares, else ''."""
    m = _TREE_MOVING_GIT.search(command)
    if not m:
        return ""
    # `git -C <path>` acts on <path>, not on the checkout the command was issued from.
    target = re.search(r"\s-C\s+(\S+)", m.group(0))
    if target:
        root = os.path.join(root, target.group(1).strip("'\""))
    hs = _open_handshake(root)
    if not hs:
        return ""
    return (f"spawn-session handshake `{hs}` is open, so two sessions share this checkout. Moving or "
            "discarding the tree here carries or destroys the other session's uncommitted work. "
            "Work in your own tree instead: `git worktree add <scratch>/<name> -b <branch> "
            "origin/main`, and remove it when the work lands. The lock lifts at `handshake close`")


# ── hook I/O glue ────────────────────────────────────────────────────────────
_TRUTHY = {"1", "true", "yes", "on"}


def _config_path(root: str) -> str | None:
    """The repo's ``.caddis/config.toml``, or ``None`` if it doesn't exist."""
    cfg = os.path.join(root, _ARTIFACT_DIR, "config.toml")
    return cfg if os.path.isfile(cfg) else None


def _load_guard_config(root: str) -> dict:
    """Parse the ``[guard]`` table from the repo's ``config.toml``; {} on any problem."""
    cfg = _config_path(root)
    if cfg is None:
        return {}
    try:
        import tomllib
        with open(cfg, "rb") as fh:
            data = tomllib.load(fh)
        section = data.get("guard", {})
        return section if isinstance(section, dict) else {}
    except Exception:
        return {}


def _load_allow(root: str) -> list[str]:
    allow = _load_guard_config(root).get("allow", [])
    return [str(x) for x in allow] if isinstance(allow, list) else []


def guard_disabled(root: str) -> bool:
    """True when the guard is turned off entirely (all tiers bypassed).

    Precedence: the env var wins (global, survives plugin auto-updates); otherwise the per-repo
    `[guard]` table — `enabled = false` or `mode = "off"`. Any parse problem → not disabled (fail safe).

    Env var: CADDIS_GUARD_DISABLED. Read silently (this runs on every tool call — no per-call warn)."""
    _disabled = os.environ.get(f"{_ENV_PREFIX}_GUARD_DISABLED", "")
    if _disabled.strip().lower() in _TRUTHY:
        return True
    section = _load_guard_config(root)
    if section.get("enabled") is False:
        return True
    if str(section.get("mode", "")).strip().lower() == "off":
        return True
    return False


def deny_only(root: str) -> bool:
    """True when the guard keeps DENY (silent hard-block of catastrophes) but suppresses the ASK tier
    (downgrades ask -> allow), so it NEVER prompts. For autonomous / no-prompt workflows that still
    want a catastrophe net: a big plan runs uninterrupted, only a truly destructive call is blocked.

    Precedence like ``guard_disabled``: env wins, then the per-repo ``[guard]`` table. Env:
    ``CADDIS_GUARD_MODE=deny-only``; config: ``[guard] mode = "deny-only"``. Read silently (runs on
    every tool call)."""
    _mode = os.environ.get(f"{_ENV_PREFIX}_GUARD_MODE", "")
    if _mode.strip().lower() == "deny-only":
        return True
    section = _load_guard_config(root)
    return str(section.get("mode", "")).strip().lower() == "deny-only"


def main() -> None:
    _reconfig = getattr(sys.stdout, "reconfigure", None)
    if _reconfig:
        try:
            _reconfig(encoding="utf-8")
        except Exception:
            pass
    try:
        data = json.load(sys.stdin)
    except Exception:
        sys.exit(0)  # never block on a malformed payload

    try:
        tool_name = data.get("tool_name", "")
        tool_input = data.get("tool_input", {})
        root = data.get("cwd") or os.getcwd()
        if guard_disabled(root):
            sys.exit(0)  # kill switch: bypass every tier, defer to normal permission handling
        tier, reason = decide(tool_name, tool_input, _load_allow(root))
        if tier != "deny" and tool_name in ("Bash", "PowerShell") and isinstance(tool_input, dict):
            lock = tree_lock_reason(str(tool_input.get("command", "")), root)
            if lock:
                tier, reason = "deny", lock
        if tier == "ask" and deny_only(root):
            tier = "allow"  # deny-only: keep catastrophe blocks, never prompt (no plan interruption)
    except Exception:
        sys.exit(0)  # any unexpected shape → fail open, never crash the tool call

    if tier in ("deny", "ask"):
        tail = (" Blocked as too dangerous to run automatically — do it by hand if you are certain."
                if tier == "deny" else " Confirm only if this is intended.")
        out = {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": tier,
                "permissionDecisionReason": f"[caddis guard] {reason}.{tail}",
            }
        }
        print(json.dumps(out))
    sys.exit(0)


if __name__ == "__main__":
    main()
