#!/usr/bin/env python3
"""caddis `guard` hook for agy (Antigravity) — PreToolUse event.

Ports claude-harness/hooks/guard.py to agy's contract: the risk CLASSIFIERS are copied in verbatim
(same tiers, same regexes, same escape hatch); only the I/O envelope is rewritten. Self-contained
(the agy bundle ships neither claude-harness/hooks/ nor scripts/), stdlib-only.

agy PreToolUse stdin (camelCase protojson):
  {"toolCall": {"name": "run_command", "args": {"CommandLine": "rm -rf /"}}, "stepIdx": N,
   "conversationId": "…", "workspacePaths": ["…"], "transcriptPath": "…", "modelName": "…"}
  NOTE: cwd is the PLUGIN dir, not the workspace — the repo root comes from workspacePaths[0].

agy PreToolUse stdout (a decision object):
  deny        -> {"decision": "deny",       "reason": "…"}   (hard block)
  ask/confirm -> {"decision": "force_ask",  "reason": "…"}   (always prompt; defeats the allow-cache)
  allow       -> nothing at all. Printing {"decision":"allow"} would *override* agy's own permission
                 prompt for that call; staying silent falls through to normal handling, which is what
                 the Claude Code guard does too.

*** FAIL OPEN — the load-bearing property of this file ***
agy may fail-closed on a hook error, so a bug here must degrade to "no guard" (agy's state today),
never to a bricked agent. Every stage is wrapped: on ANY exception, malformed payload, unknown shape
or encoding problem this prints NOTHING and exits 0. It never raises, never exits non-zero, and never
emits a partial/malformed decision (the JSON is built and serialized before a single byte is printed).

Write-tier gating (classify_write) is wired defensively: agy's file-edit tool name is still
LIVE-CHECK-PENDING (see .caddis/plans/agy-hooks-port.md), so it applies only to a tool whose name
looks like an edit/write and whose args carry a path. Unknown tools -> allow.
"""
from __future__ import annotations

import json
import os
import re
import sys

# Functional identity, mirrored from scripts/claudster_config.py.
_ARTIFACT_DIR = ".caddis"
_ENV_PREFIX = "CADDIS"

# ── protected-path rules (write → deny) ──────────────────────────────────────
_SECRET_BASENAMES = {"id_rsa", "id_dsa", "id_ecdsa", "id_ed25519", "credentials",
                     ".npmrc", ".pypirc", ".netrc", ".pgpass", ".htpasswd"}
_SECRET_SUFFIXES = (".pem", ".key", ".p12", ".pfx", ".keystore", ".jks")
_ENV_RE = re.compile(r"(^|/)\.env(\.|$)", re.I)
_ENV_EXAMPLE_RE = re.compile(r"\.env\.(example|sample|template|dist)$", re.I)

# Lockfiles are normally regenerated by the package manager, so a hand-edit is unusual enough to
# confirm. Routine manifests (package.json/tsconfig) are deliberately NOT gated — too frequent, not risky.
_ASK_BASENAMES = {"package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock", "cargo.lock",
                  "uv.lock", "composer.lock", "gemfile.lock"}
_CI_WORKFLOW_RE = re.compile(r"(^|/)(\.github|\.gitea)/workflows/", re.I)


def classify_write(file_path: str) -> tuple[str, str]:
    """Risk tier (deny|ask|allow) + reason for writing/editing ``file_path``."""
    p = file_path.replace("\\", "/")
    parts = [seg.lower() for seg in p.split("/") if seg]
    base = parts[-1] if parts else ""

    if any(seg in ("secrets", ".secrets") for seg in parts):
        return "deny", f"writes into a secrets directory ({base})"
    if ".git" in parts[:-1]:
        return "deny", "writes into the .git internal directory"
    if _ENV_RE.search(p) and not _ENV_EXAMPLE_RE.search(p):
        return "deny", f"writes an environment/secret file ({base})"
    if base in _SECRET_BASENAMES or any(base.endswith(s) for s in _SECRET_SUFFIXES):
        return "deny", f"writes a credential/key file ({base})"

    if base in _ASK_BASENAMES:
        return "ask", f"edits a lockfile ({base})"
    if _CI_WORKFLOW_RE.search(p):
        return "ask", "edits a CI/CD workflow"
    return "allow", ""


# ── bash rules ───────────────────────────────────────────────────────────────
# Catastrophic delete targets: a filesystem/home root or a *bare* drive root (C:\ ), NOT a drive
# subpath (E:\proj\dist falls through to ask).
_CATASTROPHIC_TARGET = re.compile(
    r"--no-preserve-root"
    r"|(?:^|\s)(?:/|/\*|~/|~|\$\{?HOME\}?)(?:\s|$|;|&|\|)"
    r"|(?:^|\s)[A-Za-z]:[\\/]?(?:\s|$|;|&|\|)",
    re.I,
)
_FORK_BOMB = re.compile(r":\(\)\s*\{\s*:\s*\|\s*:\s*&\s*\}\s*;\s*:")


def _strip_quotes(s: str) -> str:
    """Drop quotes so quoted flags/targets still match (rm '-rf' \"/\" → rm -rf /)."""
    return s.replace('"', "").replace("'", "")


def _has_flag(cmd: str, letter: str, longname: str) -> bool:
    """True if `cmd` carries the short flag (e.g. -rf / -r) or the long flag (--recursive)."""
    return bool(re.search(rf"(?:^|\s)-\w*{letter}\w*\b", cmd, re.I)) or longname in cmd.lower()


def _is_rm_recursive_force(cmd: str) -> bool:
    if not re.search(r"\brm\b", cmd):
        return False
    return _has_flag(cmd, "r", "--recursive") and _has_flag(cmd, "f", "--force")


def _is_win_recursive_delete(cmd: str) -> bool:
    """Native Windows recursive delete — the POSIX ``rm`` path is handled by _is_rm_recursive_force.

    Catches PowerShell ``Remove-Item -Recurse -Force`` (and the Remove-Item aliases ri/rmdir/rd/del/
    erase) plus cmd.exe ``rmdir``/``rd``/``del``/``erase`` with the ``/s`` recurse-subdirectories switch.
    This is a Windows-primary environment, so these are the real footguns the POSIX rules miss."""
    if not re.search(r"(?:^|[\s;&|(])(?:remove-item|ri|rmdir|rd|del|erase)\b", cmd, re.I):
        return False
    ps_recurse_force = bool(re.search(r"(?:^|\s)-rec\w*", cmd, re.I)) and bool(re.search(r"(?:^|\s)-for\w*", cmd, re.I))
    cmd_slash_s = bool(re.search(r"(?:^|\s)/s\b", cmd, re.I))
    return ps_recurse_force or cmd_slash_s


def classify_bash(command: str) -> tuple[str, str]:
    """Risk tier (deny|ask|allow) + reason for a shell command."""
    c = command.strip()
    cl = c.lower()
    n = _strip_quotes(c)          # quote-normalized: defeats `rm '-rf' "/"` evasion
    nl = n.lower()
    rm_rf = _is_rm_recursive_force(n)
    catastrophic = bool(_CATASTROPHIC_TARGET.search(n))
    find_delete = bool(re.search(r"\bfind\b.*?(?:-delete\b|-exec\s+rm\b)", nl))
    win_del = _is_win_recursive_delete(n)

    # ── deny: catastrophic ──
    if rm_rf and catastrophic:
        return "deny", "recursive force-delete of a root/home path (rm -rf)"
    if find_delete and catastrophic:
        return "deny", "find -delete from a root/home path"
    if win_del and catastrophic:
        return "deny", "recursive force-delete of a root/home path (Windows Remove-Item/rmdir)"
    if re.search(r"\brmtree\s*\(\s*['\"]?(?:/|~|[A-Za-z]:\\?)['\"]?\s*\)", c, re.I):
        return "deny", "recursive tree delete of a root/home path (rmtree)"
    if _FORK_BOMB.search(c):
        return "deny", "fork bomb"
    if re.search(r"\bdd\b.*\bof=/dev/", nl) or re.search(r"\bmkfs", nl) or re.search(r">\s*/dev/sd[a-z]", nl):
        return "deny", "writes directly to a disk device"
    if (re.search(r"\bchmod\b", nl) and _has_flag(n, "r", "--recursive")
            and re.search(r"\b0?777\b", nl) and catastrophic):
        return "deny", "recursive chmod 777 on a root path"

    # ── ask: destructive-but-legit ──
    if rm_rf:
        return "ask", "recursive force-delete (rm -rf)"
    if find_delete:
        return "ask", "find with -delete / -exec rm"
    if win_del:
        return "ask", "recursive delete (Windows Remove-Item -Recurse / rmdir /s)"
    # git rules tolerate intervening options (e.g. `git -c k=v push --force`) but stay within one
    # command segment (the [^;&|]* won't cross a ; && || into an unrelated command). The trailing
    # `+\S` catches a force-push via refspec (`git push origin +main`), not just the --force flags.
    if re.search(r"\bgit\b[^;&|]*\bpush\b[^;&|]*(--force\b|--force-with-lease\b|(?:^|\s)-f\b|(?:^|\s)\+\S)", c):
        return "ask", "git force-push"
    if re.search(r"\bgit\b[^;&|]*\breset\s+--hard\b", c):
        return "ask", "git reset --hard"
    if re.search(r"\bgit\b[^;&|]*\bclean\b[^;&|]*(?:^|\s)-\w*f", c):
        return "ask", "git clean (force)"
    if re.search(r"\bgit\b[^;&|]*\bfilter-(repo|branch)\b", c):
        return "ask", "git history rewrite"
    if re.search(r"\b(drop\s+(table|database|schema)|truncate\s+table)\b", cl):
        return "ask", "destructive SQL (drop/truncate)"
    if re.search(r"\b(npm|yarn|pnpm)\s+publish\b|\btwine\s+upload\b|\bcargo\s+publish\b", cl):
        return "ask", "publishing a package"
    if re.search(r"\b(curl|wget|iwr|invoke-webrequest)\b[^|]*\|\s*(sudo\s+)?(sh|bash|zsh|iex|python)\b", cl):
        return "ask", "piping a download into a shell"
    return "allow", ""


# ── agy tool-shape mapping ───────────────────────────────────────────────────
# The shell tool: step type CORTEX_STEP_TYPE_RUN_COMMAND -> "run_command". The command lives at
# args.CommandLine. Extra spellings are accepted so a step-type rename can't silently un-guard the
# shell (a missed tool name = no guard at all, which is the failure we most want to avoid).
_COMMAND_TOOLS = {"run_command", "runcommand", "run_terminal_command", "bash", "shell", "terminal"}
_COMMAND_ARG_KEYS = ("CommandLine", "commandLine", "command_line", "command", "Command")

# Write-ish tool detection is heuristic until the live check pins agy's file-edit tool name.
_WRITE_NAME_RE = re.compile(r"(edit|write|create|replace|patch|append)", re.I)
_READONLY_NAME_RE = re.compile(r"(view|read|list|search|grep|find|browser|open)", re.I)
_PATH_ARG_KEYS = ("FilePath", "filePath", "file_path", "AbsolutePath", "absolutePath",
                  "TargetFile", "targetFile", "Path", "path")


def _first_str(args: dict, keys) -> str:
    for k in keys:
        v = args.get(k)
        if isinstance(v, str) and v.strip():
            return v
    return ""


def decide(tool_name: str, args, allow_patterns: list[str]) -> tuple[str, str]:
    """Top-level decision. Classify FIRST; the allow escape hatch may only DOWNGRADE an `ask` to
    `allow` (never override a `deny`), and it matches the command/path value — not the JSON envelope —
    so a key name like "command" can't disable the guard. Never raises on a malformed payload."""
    if not isinstance(args, dict):
        return "allow", ""
    name = (tool_name or "").strip().lower()

    if name in _COMMAND_TOOLS:
        target = _first_str(args, _COMMAND_ARG_KEYS)
        tier, reason = classify_bash(target) if target else ("allow", "")
    elif _WRITE_NAME_RE.search(name) and not _READONLY_NAME_RE.search(name):
        target = _first_str(args, _PATH_ARG_KEYS)
        tier, reason = classify_write(target) if target else ("allow", "")
    else:
        return "allow", ""

    if tier == "ask" and any(pat and pat.lower() in target.lower() for pat in allow_patterns):
        return "allow", ""
    return tier, reason


# ── config (per-repo escape hatch + kill switch) ─────────────────────────────
_TRUTHY = {"1", "true", "yes", "on"}


def _config_path(root: str) -> str | None:
    """The repo's ``.caddis/config.toml``, or ``None`` if it doesn't exist."""
    cfg = os.path.join(str(root), _ARTIFACT_DIR, "config.toml")
    return cfg if os.path.isfile(cfg) else None


def _load_guard_config(root: str) -> dict:
    """Parse the ``[guard]`` table from the repo's ``config.toml``; {} on any problem."""
    cfg = _config_path(root)
    if cfg is None:
        return {}
    try:
        import tomllib
        with open(cfg, "rb") as fh:
            data = tomllib.load(fh)
        section = data.get("guard", {})
        return section if isinstance(section, dict) else {}
    except Exception:
        return {}


def _load_allow(root: str) -> list[str]:
    allow = _load_guard_config(root).get("allow", [])
    return [str(x) for x in allow] if isinstance(allow, list) else []


def guard_disabled(root: str) -> bool:
    """True when the guard is turned off entirely (all tiers bypassed).

    Precedence: the env var wins (global); otherwise the per-repo `[guard]` table — `enabled = false`
    or `mode = "off"`. Any parse problem → not disabled (fail safe). Env var: CADDIS_GUARD_DISABLED."""
    _disabled = os.environ.get(f"{_ENV_PREFIX}_GUARD_DISABLED", "")
    if _disabled.strip().lower() in _TRUTHY:
        return True
    section = _load_guard_config(root)
    if section.get("enabled") is False:
        return True
    if str(section.get("mode", "")).strip().lower() == "off":
        return True
    return False


def deny_only(root: str) -> bool:
    """True when the guard keeps DENY (silent hard-block) but suppresses the ASK tier (ask -> allow =
    silence), so it NEVER prompts — for autonomous / no-prompt workflows that still want a catastrophe
    net. Env `CADDIS_GUARD_MODE=deny-only`; config `[guard] mode = "deny-only"`. Read silently."""
    _mode = os.environ.get(f"{_ENV_PREFIX}_GUARD_MODE", "")
    if _mode.strip().lower() == "deny-only":
        return True
    section = _load_guard_config(root)
    return str(section.get("mode", "")).strip().lower() == "deny-only"


# ── hook I/O glue (agy envelope) ─────────────────────────────────────────────
_AGY_DECISION = {"deny": "deny", "ask": "force_ask"}


def _emit(tier: str, reason: str) -> None:
    """Serialize the decision FIRST, then print once — a failure mid-build can never leave agy
    reading half an object. Silence (allow) is the default for anything that isn't deny/ask."""
    decision = _AGY_DECISION.get(tier)
    if not decision:
        return
    tail = (" Blocked as too dangerous to run automatically — do it by hand if you are certain."
            if tier == "deny" else " Confirm only if this is intended.")
    payload = json.dumps({"decision": decision, "reason": f"[caddis guard] {reason}.{tail}"})
    sys.stdout.write(payload)



def _hook_note(feature, exc, root=None):
    """Record a swallowed failure in the caddis hook ledger. Never raises, never prints.

    agy hooks ship FLAT at the plugin root while hook_log.py ships under scripts/, and in
    the source repo this file sits in claude-harness/agy/ with hook_log.py one level up in
    claude-harness/scripts/. Try both layouts.
    """
    try:
        _here = os.path.dirname(os.path.abspath(__file__))
        for _cand in (os.path.join(_here, "scripts"),
                      os.path.join(os.path.dirname(_here), "scripts")):
            if os.path.isdir(_cand) and _cand not in sys.path:
                sys.path.insert(0, _cand)
        import hook_log as _hl  # noqa: E402
        _hl.record(os.path.basename(__file__).replace(".py", ""), feature, exc, root)
    except Exception as _exc:
        _hook_note("agy guard config read", _exc)

def main() -> None:
    tier, reason = "allow", ""
    try:
        _reconfig = getattr(sys.stdout, "reconfigure", None)
        if _reconfig:
            try:
                _reconfig(encoding="utf-8")
            except Exception as _exc:
                _hook_note("agy guard config read", _exc)
        try:
            data = json.load(sys.stdin)
        except Exception:
            return  # malformed payload → fail open, silently
        if not isinstance(data, dict):
            return
        call = data.get("toolCall")
        if not isinstance(call, dict):
            return
        workspaces = data.get("workspacePaths") or []
        root = workspaces[0] if isinstance(workspaces, list) and workspaces else os.getcwd()
        if guard_disabled(str(root)):
            return  # kill switch: bypass every tier
        tier, reason = decide(str(call.get("name") or ""), call.get("args"), _load_allow(str(root)))
        if tier == "ask" and deny_only(str(root)):
            tier = "allow"  # deny-only: keep catastrophe blocks, never force_ask (no plan interruption)
    except Exception:
        return  # ANY unexpected shape/error → no guard, never a crash and never a bad decision
    finally:
        try:
            _emit(tier, reason)
        except Exception as _exc:
            _hook_note("agy guard config read", _exc)
        # Always exit 0: a non-zero code from a PreToolUse hook is an agy hook *error*.
        sys.exit(0)


if __name__ == "__main__":
    main()
